services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlserver
    ports:
      - '1433:1433'
    volumes:
      - ./artifacts/mssql/:/var/opt/mssql/data
    environment:
      - SA_PASSWORD=Dev_password123
      - ACCEPT_EULA=Y